version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'pizza_ordering_system'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'

  # app:
  #   build: .
  #   command: npm run start:dev
  #   # volumes:
  #     # - .:/usr/src/app
  #     # - /usr/src/app/node_modules
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pizza_ordering_system?schema=public
  #     REDIS_HOST: redis
  # #     REDIS_PORT: 6379

volumes:
  postgres_data:
